function [rep] = getRep(filename)
% Usage: [rep] = getRep(filename)
% Function Checks the middle slice to make sure the motion is within the range
% Uses file generated by the 3dToutcount command
%
% Input: 
%     3dToutcount product file name
% Output:
%     rep   the middle the slice or a close one.  
%
% Author: Eman Ghobrial
%         fMRI center, Radiology, UC San Diego
%         April 2013
% 
%==================================================================================================
%fid = fopen('restpa_outcount.1D');
fid = fopen(filename);
A = fscanf(fid,'%d',[2,inf]);
fclose(fid);

midp = round(length(A)/2);

if A(1,midp) > A(2,midp)
     % need to check a different rep
     % get the mid range and search for a rep
     k = round((length(A)-midp)/2)
     for i = midp-k:midp+k
         if A (1,i) < A(2,i)
             rep  = i;
             break;
         else
             %cannot find a middle one with no motion
             %try an earlier one, let us just use mid point
             rep = midp;
         end
     end
else         
    rep = midp;
end    